stages:
  data_ingestion:
    cmd: python src/ml_project/components/data_ingestion.py
    deps:
      - src/ml_project/components/data_ingestion.py
    params:
      - data_ingestion.test_size
    outs:
      - data/raw
  data_preprocessing:
    cmd: python src/ml_project/components/data_preprcessing.py
    deps:
      - src/ml_project/components/data_preprcessing.py
      - data/raw
    outs:
      - data/processed

  feature_engineering:
    cmd: python src/ml_project/components/feature_engineering.py
    deps:
      - src/ml_project/components/feature_engineering.py
      - data/processed
    outs:
      - data/features
      - scaler.pkl

  model_building:
    cmd: python src/ml_project/components/model_building.py
    deps:
      - src/ml_project/components/model_building.py
      - data/features
    params:
      - model_building.learning_rate
      - model_building.max_depth
      - model_building.max_features
      - model_building.n_estimators
      - model_building.subsample
    outs:
      - model.pkl

  model_evaluation:
    cmd: python src/ml_project/components/model_evaluation.py
    deps:
      - src/ml_project/components/model_evaluation.py
      - model.pkl
    metrics:
      - metrics.json